steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'images'
      - 'import'
      - 'test-image'
      - '--source-file=gs://image-18081984/ubuntu-consul-test-stream.vmdk'
      - '--os=ubuntu-2204'
      - '--network=projects/host-project-404711/global/networks/host-vpc'
    # Add any additional flags or options as needed
options:
  pool:
    name: 'projects/svc-project-404712/locations/europe-central2/workerPools/test'
