steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'images'
      - 'import'
      - 'IMAGE_NAME'
      - '--source-file=gs://image-18081984/ubuntu-consul-test-stream.vmdk'
      - '--os=ubuntu-2204'
      - '--network=projects/host-project-404711/global/networks/host-vpc'
      # Add any additional flags or options as needed
